title: GameLab Spring 2025

description: > # this means to ignore newlines until "contact:"
  Course description.

contact:
  email: andre.henriksen@uit.no
  name: Andre Henriksen

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
